# Question 1:
### Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [2]:
import numpy as np
a = np.array([1,3,5,7])
b = np.array([2,3,4,9])

# greater
print("greater comparision b/w 2 arrays--------",a>b)
print()

# greater_equal
print("greater_equal comparision b/w 2 arrays------",a>=b)
print()

# less
print("less comparision b/w 2 arrays------",a<b)
print()

# less_equal
print("less_equal comparision b/w 2 arrays------",a<=b)

greater comparision b/w 2 arrays-------- [False False  True False]

greater_equal comparision b/w 2 arrays------ [False  True  True False]

less comparision b/w 2 arrays------ [ True False False  True]

less_equal comparision b/w 2 arrays------ [ True  True False  True]


# Question 2:
### Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives


In [3]:
zeros_10 = np.zeros(10,dtype=int)
print(zeros_10)
ones_10 = np.ones(10,dtype=int)
print(ones_10)
fives_10 = np.full((10, ), 5)
print(fives_10)

[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]
[5 5 5 5 5 5 5 5 5 5]


# Question 3:
### Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array

In [4]:
array_1 = np.array([[1,2,3],[2,3,4],[3,4,5]])
print("sum of the each three rows")
for i in range(len(array_1)):
    print("row {} sum is {}".format(i+1,sum(array_1[i])))

print("sum of the each three columns")
for i in range(len(array_1)):
    total = 0
    for j in range(len(array_1)):
        total += array_1[i][j]
    print("column {} sum is {}".format(i+1,total))
        

sum of the each three rows
row 1 sum is 6
row 2 sum is 9
row 3 sum is 12
sum of the each three columns
column 1 sum is 6
column 2 sum is 9
column 3 sum is 12


# Question 4:
### Write a NumPy program to add, subtract, multiply, divide arguments element-wise.


In [5]:
a = np.array([1,2,3,4,5])

# add
print("Addition of {} with {} is: {}".format(a,a,a+a))
print()

#sub
print("subtraction of {} from {} is: {}".format(a,a,a-a))
print()

#mul
print("multiplication of {} with {} is: {}".format(a,a,a*a))
print()

#div
print("division of {} by {} is: {}".format(a,a,a/a))


Addition of [1 2 3 4 5] with [1 2 3 4 5] is: [ 2  4  6  8 10]

subtraction of [1 2 3 4 5] from [1 2 3 4 5] is: [0 0 0 0 0]

multiplication of [1 2 3 4 5] with [1 2 3 4 5] is: [ 1  4  9 16 25]

division of [1 2 3 4 5] by [1 2 3 4 5] is: [1. 1. 1. 1. 1.]


# Question 5:
### Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in degree.


In [6]:
import math

x = int(input("enter value in terms of degrees : "))
print()

print("sine value of given {} degree is : {} ".format(x,math.sin(x/57.2957795)))
print()

print("cosine value of given {} degree is : {} ".format(x,math.cos(x/57.2957795)))
print()


print("tangent value of given {} degree is : {} ".format(x,math.tan(x/57.2957795)))

enter value in terms of degrees : 45

sine value of given 45 degree is : 0.7071067813133527 

cosine value of given 45 degree is : 0.7071067810597423 

tangent value of given 45 degree is : 1.0000000003586593 


# Question 6:
### Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the index labels

In [11]:
import pandas as pd
students = {'name':['sai','krish','deeksh'],'marks':[40,75,100]}
x = pd.DataFrame(students)
x

name  marks
0     sai     40
1   krish     75
2  deeksh    100

# Question 7:
### Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.


In [12]:
# select name column
x['name']

0       sai
1     krish
2    deeksh
Name: name, dtype: object

In [13]:
# select score column
x['marks']

0     40
1     75
2    100
Name: marks, dtype: int64

# Question 8:
### Write a Pandas program to join the two given dataframes along rows and assign all data.

In [17]:
pd.concat([x,x])

name  marks
0     sai     40
1   krish     75
2  deeksh    100
0     sai     40
1   krish     75
2  deeksh    100

# Question 9:
### Write a Pandas program to detect missing values of a given DataFrame. Display True or False

In [18]:
x.isnull()

name  marks
0  False  False
1  False  False
2  False  False

# Question 10:
### Write a Pandas program to create and display a one-dimensional array-like object containing an array of data.

In [19]:
x.to_numpy()

array([['sai', 40],
       ['krish', 75],
       ['deeksh', 100]], dtype=object)